name: MLFlow Model Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow tensorflow scikit-learn opencv-python imutils

      - name: Train and log model
        run: |
          python train.py

      - name: Deploy model
        run: |
          mlflow models serve -m "runs:/$(mlflow runs list --no-conda | grep -oP '(?<=runs:/)[^ ]+' | head -n 1)/mask_detector_model" -p 1234